export const products = [
  {
    id: "ai-book",
    name: "小广 AI 小课堂",
    spec: "B5 · 72p 学术合刊",
    price: 25,
    image: "./assets/book.webp",
    alt: "小广 AI 小课堂新刊封面",
  },
  {
    id: "eye-mask",
    name: "筱泽广眼罩",
    spec: "226 × 121 mm · 附蓝色收纳袋",
    price: 20,
    image: "./assets/eye-mask.webp",
    alt: "筱泽广困倦眼神造型眼罩",
  },
  {
    id: "rabbit-stand",
    name: "兔兔小广大立牌",
    spec: "约 108 × 152 mm",
    price: 30,
    image: "./assets/rabbit-stand.webp",
    alt: "抱着趴趴广的兔耳少女亚克力立牌",
  },
  {
    id: "shikishi-kotone",
    name: "触感膜色纸 · 藤田琴音",
    spec: "流沙银边 · 14 × 14 cm",
    price: 15,
    image: "./assets/shikishi-kotone.webp",
    alt: "藤田琴音款触感膜色纸",
  },
  {
    id: "shikishi-hiro",
    name: "触感膜色纸 · 筱泽广",
    spec: "流沙银边 · 14 × 14 cm",
    price: 15,
    image: "./assets/shikishi-hiro.webp",
    alt: "筱泽广款触感膜色纸",
  },
  {
    id: "pvc-kotone",
    name: "PVC 透卡 · 藤田琴音",
    spec: "86 × 54 mm · 彩白透卡",
    price: 8,
    image: "./assets/pvc-kotone.webp",
    alt: "藤田琴音款 PVC 透明卡片",
  },
  {
    id: "pvc-hiro",
    name: "PVC 透卡 · 筱泽广",
    spec: "86 × 54 mm · 彩白透卡",
    price: 8,
    image: "./assets/pvc-hiro.webp",
    alt: "筱泽广款 PVC 透明卡片",
  },
  {
    id: "badge-kotone",
    name: "双闪吧唧 · 藤田琴音",
    spec: "58 × 58 mm",
    price: 12,
    image: "./assets/badge-kotone.webp",
    alt: "藤田琴音款双闪吧唧",
  },
  {
    id: "badge-hiro",
    name: "双闪吧唧 · 筱泽广",
    spec: "58 × 58 mm",
    price: 12,
    image: "./assets/badge-hiro.webp",
    alt: "筱泽广款双闪吧唧",
  },
  {
    id: "window-hiro",
    name: "QQ 人彩窗立牌 · 筱泽广",
    spec: "75 × 59 mm · CNC",
    price: 18,
    image: "./assets/window-hiro.webp",
    alt: "筱泽广款 QQ 人彩窗立牌",
  },
  {
    id: "window-china",
    name: "QQ 人彩窗立牌 · 仓本千奈",
    spec: "75 × 59 mm · CNC",
    price: 18,
    image: "./assets/window-china.webp",
    alt: "仓本千奈款 QQ 人彩窗立牌",
  },
  {
    id: "window-kotone",
    name: "QQ 人彩窗立牌 · 藤田琴音",
    spec: "75 × 59 mm · CNC",
    price: 18,
    image: "./assets/window-kotone.webp",
    alt: "藤田琴音款 QQ 人彩窗立牌",
  },
  {
    id: "window-misuzu",
    name: "QQ 人彩窗立牌 · 秦谷美铃",
    spec: "75 × 59 mm · CNC",
    price: 18,
    image: "./assets/window-misuzu.webp",
    alt: "秦谷美铃款 QQ 人彩窗立牌",
  },
  {
    id: "window-lilja",
    name: "QQ 人彩窗立牌 · 葛城莉莉娅",
    spec: "75 × 59 mm · CNC",
    price: 18,
    image: "./assets/window-lilja.webp",
    alt: "葛城莉莉娅款 QQ 人彩窗立牌",
  },
  {
    id: "spring-misuzu",
    name: "摇摇乐立牌 · 秦谷美铃",
    spec: "65 × 46 mm · 可粘贴",
    price: 15,
    image: "./assets/spring-misuzu.webp",
    alt: "秦谷美铃款摇摇乐立牌",
  },
  {
    id: "spring-hiro",
    name: "摇摇乐立牌 · 筱泽广",
    spec: "65 × 46 mm · 可粘贴",
    price: 15,
    image: "./assets/spring-hiro.webp",
    alt: "筱泽广款摇摇乐立牌",
  },
  {
    id: "spring-kotone",
    name: "摇摇乐立牌 · 藤田琴音",
    spec: "65 × 46 mm · 可粘贴",
    price: 15,
    image: "./assets/spring-kotone.webp",
    alt: "藤田琴音款摇摇乐立牌",
  },
  {
    id: "spring-lilja",
    name: "摇摇乐立牌 · 葛城莉莉娅",
    spec: "65 × 46 mm · 可粘贴",
    price: 15,
    image: "./assets/spring-lilja.webp",
    alt: "葛城莉莉娅款摇摇乐立牌",
  },
  {
    id: "ride-stand",
    name: "「现代舞」小车立牌",
    spec: "约 75 × 59 mm",
    price: 12,
    image: "./assets/ride-stand.webp",
    alt: "筱泽广现代舞造型小车立牌",
  },
  {
    id: "whisper-stand",
    name: "广千双人立牌",
    spec: "约 75 × 59 mm · 双人款",
    price: 15,
    image: "./assets/whisper-stand.webp",
    alt: "筱泽广与仓本千奈双人立牌",
  },
  {
    id: "ktn-shikishi",
    name: "琴音马卡龙中色纸",
    spec: "14 × 14 cm · 细闪",
    price: 15,
    image: "./assets/ktn-shikishi.webp",
    alt: "马卡龙主题藤田琴音细闪色纸",
  },
  {
    id: "ktn-badge",
    name: "琴音马卡龙徽章",
    spec: "亮膜徽章",
    price: 8,
    image: "./assets/ktn-badge.webp",
    alt: "马卡龙主题藤田琴音亮膜徽章",
  },
];

export const productById = new Map(products.map((product) => [product.id, product]));
