server {
    listen 80;
    listen [::]:80;
    server_name api.matto.top;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.matto.top;
    ssl_certificate /etc/nginx/ssl/api.matto.top_P256/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/api.matto.top_P256/private.key;

    location = /hiro-order {
        return 308 /hiro-order/;
    }

    location /hiro-order/ {
        proxy_pass http://127.0.0.1:19120/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 15s;
        client_max_body_size 32k;
    }

    location / {
        proxy_pass http://127.0.0.1:2333;
    }
}
